source 'https://github.com/CocoaPods/Specs.git'
platform :ios, “8.1”
use_frameworks!

target “Tqube taxi Driver” do

pod 'Localize-Swift', '~> 1.1'
pod 'GoogleMaps'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'Bolts'
end