<?php defined('SYSPATH') or die("No direct access allowed");
define("TABLE_PREFIX","");

# MongoDB Collection Names
define("SITEINFO",TABLE_PREFIX."siteinfo");
define("MDB_CMS",TABLE_PREFIX."cms_menu");
define("MDB_CONTACTS",TABLE_PREFIX."contacts");
define("MDB_CSC",TABLE_PREFIX."csc");
define("MDB_COMPANY",TABLE_PREFIX."company");
define("MDB_DISPATCH_ALGORITHM",TABLE_PREFIX."dispatch_algorithm");
define("MDB_DRIVER_INFO",TABLE_PREFIX."driver_driverinfo");
define("MDB_LOCATION_HISTORY",TABLE_PREFIX."driver_location_history");
define("MDB_REJECTION_HISTORY",TABLE_PREFIX."driver_rejection_list");
define("MDB_REQUEST_HISTORY",TABLE_PREFIX."driver_request_details");
define("MDB_SHIFT_HISTORY",TABLE_PREFIX."driver_shift_history");
define("MDB_LOGS",TABLE_PREFIX."logs");
define("MDB_MOTOR_MODEL",TABLE_PREFIX."motor_model");
define("MDB_PASSENGERS",TABLE_PREFIX."passengers");
define("MDB_PASSENGERS_FAVOURITES",TABLE_PREFIX."passengers_favourites");
define("MDB_PASSENGERS_LOGS",TABLE_PREFIX."passengers_logs");
define("MDB_PASSENGERS_PROMO",TABLE_PREFIX."passengers_promo");
define("MDB_PASSENGER_REFERRAL",TABLE_PREFIX."passengers_referral");
define("MDB_PAYMENT_TYPES",TABLE_PREFIX."payment_gateway_types");
define("MDB_PAYMENT_GATEWAYS",TABLE_PREFIX."payments_gateways");
define("MDB_PAYMENT_MODULES",TABLE_PREFIX."payment_modules");
define("MDB_PASSENGER_WALLET_LOG",TABLE_PREFIX."passengers_wallet_log");
define("MDB_DRIVER_WALLET_LOG",TABLE_PREFIX."drivers_wallet_log");
define("MDB_PEOPLE",TABLE_PREFIX."people");
define("MDB_SITEINFO",TABLE_PREFIX."siteinfo");
define("MDB_SMS_TEMPLATES",TABLE_PREFIX."sms_template");
define("MDB_TEMPLATES",TABLE_PREFIX."sms_template");
define("MDB_SMTP_SETTINGS",TABLE_PREFIX."smtp_settings");
define("MDB_TAXI",TABLE_PREFIX."taxi");
define("MDB_TAXI_DRIVER_MAPPING",TABLE_PREFIX."taxi_driver_mapping");
define("MDB_TRANSACTION",TABLE_PREFIX."transaction");
define("MDB_PASSENGERS_FAQ",TABLE_PREFIX."faq");
define("MDB_SUBSCRIBE",TABLE_PREFIX."subscribe");
define("MDB_SPLIT_LOG",TABLE_PREFIX."passenger_split_log");
define("MDB_FAILED_TRANSACTION",TABLE_PREFIX."passenger_failed_transaction");
define("MDB_DRIVER_REF",TABLE_PREFIX."driver_referral_list");
define("MDB_DRIVER_WALLET_REQ",TABLE_PREFIX."driver_wallet_requests");
define("MDB_WITHDRAW_REQUEST",TABLE_PREFIX."withdraw_request");
define("MDB_WITHDRAW_REQUEST_LOGS",TABLE_PREFIX."withdraw_request_logs");
define("MDB_WITHDRAW_PAYMENT_MODE",TABLE_PREFIX."withdraw_payment_mode");
define("MDB_MOTOR_COMPANY",TABLE_PREFIX."motor_company");
define("MDB_COMPANY_DOMAIN",TABLE_PREFIX."company_domain");
define("MDB_HELP",TABLE_PREFIX."help_contents");
define("MDB_PACKAGE_INFO", TABLE_PREFIX."package_info");
define("MDB_SMS_SETTINGS", TABLE_PREFIX."company_sms_settings");
define("MDB_BILLING_INFO", TABLE_PREFIX."billing_info");
define("MDB_BILLING_REG_INFO",TABLE_PREFIX."billing_reg_info");
define("MDB_PACKAGE_ACCT_TRANS",TABLE_PREFIX."package_account_transaction");
define("MDB_POPULAR_PLACES",TABLE_PREFIX."popular_places");
define("MDB_THEME_SETTINGS",TABLE_PREFIX."theme_settings");
define("MDB_EMAIL_TEMPLATES",TABLE_PREFIX."email_template");
define("MDB_DRIVER_WALLET_AMOUNT_LOG",TABLE_PREFIX."driver_wallet_amount_log");
define("MDB_DRIVER_WALLET_DEDUCTION_LOG",TABLE_PREFIX."driver_wallet_deduction_log");

?>
