<?php

echo phpinfo();exit;
//echo gmdate('Y-m-d');exit;
/*
$sec = strtotime('2017-06-06 07:26:00');
$date = new DateTime('@'.$sec, new DateTimeZone('America/Montevideo'));
$date->setTimezone(new DateTimeZone('America/New_York'));
print_r($date);
echo $date->format($dateformate);

exit; */
$array1 = array(
'Afghanistan'=>'AFN',
'Albania'=>'ALL',
'Algeria'=>'DZD',
'American Samoa'=>'USD',
'Andorra'=>'EUR',
'Angola'=>'AOA',
'Anguilla'=>'XCD',
'Antarctica'=>'',
'Antigua And Barbuda'=>'XCD',
'Argentina'=>'ARS',
'Armenia'=>'AMD',
'Aruba'=>'AWG',
'Australia'=>'AUD',
'Austria'=>'EUR',
'Azerbaijan'=>'AZN',
'Bahamas (The)'=>'BSD',
'Bahrain'=>'BHD',
'Bangladesh'=>'BDT',
'Barbados'=>'BBD',
'Belarus'=>'BYR',
'Belgium'=>'EUR',
'Belize'=>'BZD',
'Benin'=>'XOF',
'Bermuda'=>'BMD',
'Bhutan'=>'BTN',
'Bhutan'=>'INR',
'Bolivia (Plurinational State Of)'=>'BOB',
'Bolivia (Plurinational State Of)'=>'BOV',
'Bonaire, Sint Eustatius And Saba'=>'USD',
'Bosnia And Herzegovina'=>'BAM',
'Botswana'=>'BWP',
'Bouvet Island'=>'NOK',
'Brazil'=>'BRL',
'British Indian Ocean Territory (The)'=>'USD',
'Brunei Darussalam'=>'BND',
'Bulgaria'=>'BGN',
'Burkina Faso'=>'XOF',
'Burundi'=>'BIF',
'Cabo Verde'=>'CVE',
'Cambodia'=>'KHR',
'Cameroon'=>'XAF',
'Canada'=>'CAD',
'Cayman Islands (The)'=>'KYD',
'Central African Republic (The)'=>'XAF',
'Chad'=>'XAF',
'Chile'=>'CLF',
'Chile'=>'CLP',
'China'=>'CNY',
'Christmas Island'=>'AUD',
'Cocos (Keeling) Islands (The)'=>'AUD',
'Colombia'=>'COP',
'Colombia'=>'COU',
'Comoros (The)'=>'KMF',
'Congo (The Democratic Republic Of The)'=>'CDF',
'Congo (The)'=>'XAF',
'Cook Islands (The)'=>'NZD',
'Costa Rica'=>'CRC',
'Croatia'=>'HRK',
'Cuba'=>'CUC',
'Cuba'=>'CUP',
'Curaçao'=>'ANG',
'Cyprus'=>'EUR',
'Czech Republic (The)'=>'CZK',
'Denmark'=>'DKK',
'Djibouti'=>'DJF',
'Dominica'=>'XCD',
'Dominican Republic (The)'=>'DOP',
'Ecuador'=>'USD',
'Egypt'=>'EGP',
'El Salvador'=>'SVC',
'El Salvador'=>'USD',
'Equatorial Guinea'=>'XAF',
'Eritrea'=>'ERN',
'Estonia'=>'EUR',
'Ethiopia'=>'ETB',
'European Union'=>'EUR',
'Falkland Islands (The) [Malvinas]'=>'FKP',
'Faroe Islands (The)'=>'DKK',
'Fiji'=>'FJD',
'Finland'=>'EUR',
'France'=>'EUR',
'French Guiana'=>'EUR',
'French Polynesia'=>'XPF',
'French Southern Territories (The)'=>'EUR',
'Gabon'=>'XAF',
'Gambia (The)'=>'GMD',
'Georgia'=>'GEL',
'Germany'=>'EUR',
'Ghana'=>'GHS',
'Gibraltar'=>'GIP',
'Greece'=>'EUR',
'Greenland'=>'DKK',
'Grenada'=>'XCD',
'Guadeloupe'=>'EUR',
'Guam'=>'USD',
'Guatemala'=>'GTQ',
'Guernsey'=>'GBP',
'Guinea'=>'GNF',
'Guinea-Bissau'=>'XOF',
'Guyana'=>'GYD',
'Haiti'=>'HTG',
'Haiti'=>'USD',
'Heard Island And Mcdonald Islands'=>'AUD',
'Holy See (The)'=>'EUR',
'Honduras'=>'HNL',
'Hong Kong'=>'HKD',
'Hungary'=>'HUF',
'Iceland'=>'ISK',
'India'=>'INR',
'Indonesia'=>'IDR',
'International Monetary Fund (Imf)'=>'XDR',
'Iran (Islamic Republic Of)'=>'IRR',
'Iraq'=>'IQD',
'Ireland'=>'EUR',
'Isle Of Man'=>'GBP',
'Israel'=>'ILS',
'Italy'=>'EUR',
'Jamaica'=>'JMD',
'Japan'=>'JPY',
'Jersey'=>'GBP',
'Jordan'=>'JOD',
'Kazakhstan'=>'KZT',
'Kenya'=>'KES',
'Kiribati'=>'AUD',
'Korea (The Democratic People’S Republic Of)'=>'KPW',
'Korea (The Republic Of)'=>'KRW',
'Kuwait'=>'KWD',
'Kyrgyzstan'=>'KGS',
'Lao People’S Democratic Republic (The)'=>'LAK',
'Latvia'=>'EUR',
'Lebanon'=>'LBP',
'Lesotho'=>'LSL',
'Lesotho'=>'ZAR',
'Liberia'=>'LRD',
'Libya'=>'LYD',
'Liechtenstein'=>'CHF',
'Lithuania'=>'EUR',
'Luxembourg'=>'EUR',
'Macao'=>'MOP',
'Macedonia (The Former Yugoslav Republic Of)'=>'MKD',
'Madagascar'=>'MGA',
'Malawi'=>'MWK',
'Malaysia'=>'MYR',
'Maldives'=>'MVR',
'Mali'=>'XOF',
'Malta'=>'EUR',
'Marshall Islands (The)'=>'USD',
'Martinique'=>'EUR',
'Mauritania'=>'MRO',
'Mauritius'=>'MUR',
'Mayotte'=>'EUR',
'Member Countries Of The African Development Bank Group'=>'XUA',
'Mexico'=>'MXN',
'Mexico'=>'MXV',
'Micronesia (Federated States Of)'=>'USD',
'Moldova (The Republic Of)'=>'MDL',
'Monaco'=>'EUR',
'Mongolia'=>'MNT',
'Montenegro'=>'EUR',
'Montserrat'=>'XCD',
'Morocco'=>'MAD',
'Mozambique'=>'MZN',
'Myanmar'=>'MMK',
'Namibia'=>'NAD',
'Namibia'=>'ZAR',
'Nauru'=>'AUD',
'Nepal'=>'NPR',
'Netherlands (The)'=>'EUR',
'New Caledonia'=>'XPF',
'New Zealand'=>'NZD',
'Nicaragua'=>'NIO',
'Niger (The)'=>'XOF',
'Nigeria'=>'NGN',
'Niue'=>'NZD',
'Norfolk Island'=>'AUD',
'Northern Mariana Islands (The)'=>'USD',
'Norway'=>'NOK',
'Oman'=>'OMR',
'Pakistan'=>'PKR',
'Palau'=>'USD',
'Palestine, State Of'=>'',
'Panama'=>'PAB',
'Panama'=>'USD',
'Papua New Guinea'=>'PGK',
'Paraguay'=>'PYG',
'Peru'=>'PEN',
'Philippines (The)'=>'PHP',
'Pitcairn'=>'NZD',
'Poland'=>'PLN',
'Portugal'=>'EUR',
'Puerto Rico'=>'USD',
'Qatar'=>'QAR',
'Romania'=>'RON',
'Russian Federation (The)'=>'RUB',
'Rwanda'=>'RWF',
'Réunion'=>'EUR',
'Saint Barthélemy'=>'EUR',
'Saint Helena, Ascension And Tristan Da Cunha'=>'SHP',
'Saint Kitts And Nevis'=>'XCD',
'Saint Lucia'=>'XCD',
'Saint Martin (French Part)'=>'EUR',
'Saint Pierre And Miquelon'=>'EUR',
'Saint Vincent And The Grenadines'=>'XCD',
'Samoa'=>'WST',
'San Marino'=>'EUR',
'Sao Tome And Principe'=>'STD',
'Saudi Arabia'=>'SAR',
'Senegal'=>'XOF',
'Serbia'=>'RSD',
'Seychelles'=>'SCR',
'Sierra Leone'=>'SLL',
'Singapore'=>'SGD',
'Sint Maarten (Dutch Part)'=>'ANG',
'Sistema Unitario De Compensacion Regional De Pagos "Sucre"'=>'XSU',
'Slovakia'=>'EUR',
'Slovenia'=>'EUR',
'Solomon Islands'=>'SBD',
'Somalia'=>'SOS',
'South Africa'=>'ZAR',
'South Georgia And The South Sandwich Islands'=>'',
'South Sudan'=>'SSP',
'Spain'=>'EUR',
'Sri Lanka'=>'LKR',
'Sudan (The)'=>'SDG',
'Suriname'=>'SRD',
'Svalbard And Jan Mayen'=>'NOK',
'Swaziland'=>'SZL',
'Sweden'=>'SEK',
'Switzerland'=>'CHE',
'Switzerland'=>'CHF',
'Switzerland'=>'CHW',
'Syrian Arab Republic'=>'SYP',
'Taiwan (Province Of China)'=>'TWD',
'Tajikistan'=>'TJS',
'Tanzania, United Republic Of'=>'TZS',
'Thailand'=>'THB',
'Timor-Leste'=>'USD',
'Togo'=>'XOF',
'Tokelau'=>'NZD',
'Tonga'=>'TOP',
'Trinidad And Tobago'=>'TTD',
'Tunisia'=>'TND',
'Turkey'=>'TRY',
'Turkmenistan'=>'TMT',
'Turks And Caicos Islands (The)'=>'USD',
'Tuvalu'=>'AUD',
'Uganda'=>'UGX',
'Ukraine'=>'UAH',
'United Arab Emirates (The)'=>'AED',
'United Kingdom Of Great Britain And Northern Ireland (The)'=>'GBP',
'United States Minor Outlying Islands (The)'=>'USD',
'United States Of America (The)'=>'USD',
'United States Of America (The)'=>'USN',
'Uruguay'=>'UYI',
'Uruguay'=>'UYU',
'Uzbekistan'=>'UZS',
'Vanuatu'=>'VUV',
'Venezuela (Bolivarian Republic Of)'=>'VEF',
'Viet Nam'=>'VND',
'Virgin Islands (British)'=>'USD',
'Virgin Islands (U.S.)'=>'USD',
'Wallis And Futuna'=>'XPF',
'Western Sahara'=>'MAD',
'Yemen'=>'YER',
'Zambia'=>'ZMW',
'Zimbabwe'=>'ZWL',
'Åland Islands'=>'EUR',
);

$array2 = array('Afghanistan',
'Albania',
'Algeria',
'America',
'American Samoa',
'Andorra',
'Anguilla',
'Antarctica',
'Antigua and Barbuda',
'Argentina',
'Armenia',
'Aruba',
'Australia',
'Austria',
'Azerbaijan',
'Bahamas',
'Bahrain',
'Barbados',
'Belarus',
'Belgium',
'Belize',
'Benin',
'Bermuda',
'Bhutan',
'Bolivia',
'Bosnia and Herzegovina',
'Botswana',
'Bouvet Island',
'Brasil',
'British Indian Ocean Territory',
'British Virgin Islands',
'Brunei',
'Bulgaria',
'Burkina Faso',
'Burundi',
'Cambodia',
'Cameroon',
'Canada',
'Cape Verde',
'Cayman Islands',
'Central African Republic',
'Chad',
'Chile',
'China',
'China',
'Christmas Island',
'Cocos Islands',
'Colombia',
'Comoros',
'Cook Islands',
'Costa Rica',
'Croatia',
'Cuba',
'Cyprus',
'Czech Republic',
'Democratic Republic of the Congo',
'Djibouti',
'Dominica',
'Dominican Republic',
'Dubai',
'East Timor',
'Ecuador',
'Egypt',
'El Salvador',
'Equatorial Guinea',
'Eritrea',
'Estonia',
'Ethiopia',
'Falkland Islands',
'Faroe Islands',
'Fiji',
'Finland',
'France',
'French Guiana',
'French Polynesia',
'French Southern Territories',
'Gabon',
'Gambia',
'Georgia',
'German',
'Germany',
'Ghana',
'Gibraltar',
'Greece',
'Greenland',
'Grenada',
'Guadeloupe',
'Guam',
'Guatemala',
'Guinea',
'Guinea-Bissau',
'Guyana',
'Haiti',
'Heard Island and McDonald Islands',
'Honduras',
'Hong Kong',
'Hungary',
'Iceland',
'India',
'Iran',
'Iraq',
'Ireland',
'Israel',
'Italy',
'Ivory Coast',
'Jamaica',
'Japan',
'Jordan',
'Kazakhstan',
'KENYA',
'Kiribati',
'Kyrgyzstan',
'Laos',
'Latvia',
'Lesotho',
'Liberia',
'Libya',
'Liechtenstein',
'Lithuania',
'Luxembourg',
'Macao',
'Macedonia',
'Madagascar',
'Malawi',
'Malaysia',
'Maldives',
'Mali',
'Malta',
'Marshall Islands',
'Martinique',
'Mauritania',
'Mauritius',
'Mayotte',
'Mexico',
'Mexico',
'Micronesia',
'Moldova',
'Monaco',
'Mongolia',
'Montserrat',
'Morocco',
'Mourisious',
'Mozambique',
'Namibia',
'Nauru',
'Nepal',
'Netherlands',
'Netherlands Antilles',
'New Caledonia',
'New Zealand',
'Nicaragua',
'Niger',
'Nigeria',
'Niue',
'Norfolk Island',
'North Korea',
'Northern Mariana Islands',
'Norway',
'Oman',
'Pakistan',
'Palau',
'Palestinian Territory',
'Panama',
'Papua New Guinea',
'Paraguay',
'Peru',
'Philippines',
'Pitcairn',
'Poland',
'Portugal',
'Puerto Rico',
'Qatar',
'Republic of the Congo',
'Reunion',
'Romania',
'Russia',
'Russian Federation',
'Rwanda',
'Saint Helena',
'Saint Kitts and Nevis',
'Saint Lucia',
'Saint Pierre and Miquelon',
'Saint Vincent and the Grenadines',
'Samoa',
'San Marino',
'Sao Tome and Principe',
'Saudi Arabia',
'Schweiz',
'Senegal',
'Serbia and Montenegro',
'Seychelles',
'Sierra Leone',
'Singapore',
'Slovakia',
'Slovenia',
'Solomon Islands',
'Somalia',
'South Africa',
'South Georgia and the South Sandwich Islands',
'South Korea',
'Spain',
'Sri Lanka',
'Sudan',
'Suriname',
'Svalbard and Jan Mayen',
'Swaziland',
'Sweden',
'Switzerland',
'Syria',
'Taiwan',
'Tajikistan',
'Tanzania',
'test',
'testcountr',
'testcountry',
'testing',
'testing service',
'Togo',
'Tokelau',
'Tonga',
'Trinidad and Tobago',
'Tunisia',
'Turkey',
'Turkmenistan',
'Turks and Caicos Islands',
'Tuvalu',
'U.S. Virgin Islands',
'Uganda',
'Ukraine',
'United Kingdom',
'United Kingdoms',
'United States',
'United States Minor Outlying Islands',
'Uruguay',
'Uzbekistan',
'Vanuatu',
'Vatican',
'Venezuela',
'Vietnam',
'Wallis and Futuna',
'Western Sahara',
'Yemen',
'Zambia',
'Zimbabwe');
$matched = $result = [];

foreach($array1 as $key => $value){
	foreach($array2 as $value2){
		($key == $value2) ? $matched[$value2] = $value : '';
	}
}

foreach($array2 as $countryname){
	$result[$countryname] = (array_key_exists($countryname, $matched)) ? $matched[$countryname] : '';
}
//~ $matched = array_keys($matched);
//~ $unmatched = array_diff($array2, $matched);
echo '<pre>';print_r($result);exit;
?>
